--Dados tabela cliente 


INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Fernanda','35018656923','Fazenda Maria Fernanda');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Nicole','35122401393','Fazenda Nicole');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Tomás','35579691025','Fazenda Tomás');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Alícia','35567333925','Fazenda Alícia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Arthur','35376527766','Fazenda Arthur');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Flor','35628598690','Fazenda Maria Flor');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Laís','35658481883','Fazenda Laís');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Júlia','35271923690','Fazenda Ana Júlia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Vicente','35065814684','Fazenda Vicente');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Luana','35112051139','Fazenda Luana');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Agatha','35723815275','Fazenda Agatha');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Davi Lucca','35068640119','Fazenda Davi Lucca');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Isadora','35817012236','Fazenda Isadora');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Luiza','35834115743','Fazenda Ana Luiza');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Laura','35749514625','Fazenda Laura');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Pedro Lucas','35848649872','Fazenda Pedro Lucas');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Beatriz','35918320904','Fazenda Ana Beatriz');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Liz','35317279641','Fazenda Ana Liz');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Rafael','35106971858','Fazenda Rafael');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Sophia','35072915905','Fazenda Sophia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Fernando','35395123098','Fazenda Fernando');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Clarice','35193890986','Fazenda Clarice');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Arthur Henrique','35976167667','Fazenda Arthur Henrique');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Guilherme','35012634043','Fazenda Guilherme');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Alice','35658047135','Fazenda Maria Alice');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Luiz Miguel','35255862538','Fazenda Luiz Miguel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Lívia','35695868262','Fazenda Ana Lívia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('João Gabriel','35491395119','Fazenda João Gabriel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Oliver','35921408762','Fazenda Oliver');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Gabrielly','35985461388','Fazenda Gabrielly');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Thomas','35535664276','Fazenda Thomas');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Emanuel','35454605571','Fazenda Emanuel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Victor','35315961190','Fazenda Victor');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Lorena','35553029557','Fazenda Lorena');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Emanuelly','35726286734','Fazenda Emanuelly');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Helena','35080676795','Fazenda Helena');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Enzo','35903216261','Fazenda Enzo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Beatriz','35782401185','Fazenda Beatriz');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria-','35753711390','Fazenda Maria-');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Felipe','35709130757','Fazenda Felipe');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Fernanda','35647998006','Fazenda Fernanda');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Elisa','35541913042','Fazenda Elisa');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Marina','35301325390','Fazenda Marina');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Heloise','35875565465','Fazenda Heloise');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Eduarda','35214306710','Fazenda Eduarda');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Carlos Eduardo','35240472912','Fazenda Carlos Eduardo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Murilo','35208864301','Fazenda Murilo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Clara','35130670241','Fazenda Clara');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Isis','35447595886','Fazenda Maria Isis');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Cauã','35981768208','Fazenda Cauã');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Anthony Gabriel','35907965099','Fazenda Anthony Gabriel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Thiago','35246096575','Fazenda Thiago');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Clara','35840027847','Fazenda Maria Clara');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Enzo Miguel','35778564064','Fazenda Enzo Miguel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Yasmin','35974574132','Fazenda Yasmin');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Luiz Otávio','35411513298','Fazenda Luiz Otávio');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Alice','35768514021','Fazenda Alice');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Luiza','35202769182','Fazenda Luiza');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Lara','35575626056','Fazenda Lara');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Daniel','35644496908','Fazenda Daniel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Isaac','35412689607','Fazenda Isaac');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Heloísa','35426999695','Fazenda Maria Heloísa');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('André','35826376976','Fazenda André');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Noah','35819187047','Fazenda Noah');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Otávio','35410119078','Fazenda Otávio');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Matheus','35079706393','Fazenda Matheus');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Davi','35721730435','Fazenda Davi');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Gael','35194105013','Fazenda Gael');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Lucas Gabriel','35836706346','Fazenda Lucas Gabriel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Mariana','35439602756','Fazenda Mariana');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Davi Lucas','35771282784','Fazenda Davi Lucas');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Antonella','35824495030','Fazenda Antonella');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Malu','35150021396','Fazenda Malu');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Lavínia','35147375644','Fazenda Lavínia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('José','35632172786','Fazenda José');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('João Pedro','35583695724','Fazenda João Pedro');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Melissa','35369006661','Fazenda Melissa');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Levi','35674982260','Fazenda Levi');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Larissa','35357626299','Fazenda Larissa');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Analu','35423423099','Fazenda Analu');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Benício','35069558784','Fazenda Benício');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Sophia','35783455175','Fazenda Ana Sophia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Heitor','35402745044','Fazenda Heitor');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maya','35656602580','Fazenda Maya');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Gustavo','35589934542','Fazenda Gustavo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Lívia','35560745349','Fazenda Lívia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Heloísa','35564234482','Fazenda Heloísa');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Cecília','35983877231','Fazenda Maria Cecília');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Pietro','35361445980','Fazenda Pietro');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Martin','35666089527','Fazenda Martin');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Rebeca','35877254988','Fazenda Rebeca');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Giovanna','35318562061','Fazenda Giovanna');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maitê','35577185148','Fazenda Maitê');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Catarina','35266991490','Fazenda Catarina');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana','35034881197','Fazenda Ana');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Victor Hugo','35030759363','Fazenda Victor Hugo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Gabriel','35558258397','Fazenda Gabriel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Vinícius','35278766886','Fazenda Vinícius');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Miguel Henrique','35169145072','Fazenda Miguel Henrique');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Davi Miguel','35980805645','Fazenda Davi Miguel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Isabella','37796374453','Fazenda Isabella');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Cecília','37485362509','Fazenda Ana Cecília');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Lucas','37743704622','Fazenda Lucas');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Bernardo','37301938374','Fazenda Bernardo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Bruna','37685221482','Fazenda Bruna');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Antônia','37307678141','Fazenda Antônia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Leonardo','37643736674','Fazenda Leonardo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Esther','37419932170','Fazenda Esther');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Miguel','37133901715','Fazenda Miguel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Laura','37413897564','Fazenda Ana Laura');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Pedro','37680683991','Fazenda Pedro');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Caio','37323713895','Fazenda Caio');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Erick','37896286932','Fazenda Erick');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Anthony','37293361651','Fazenda Anthony');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Bento','37540922312','Fazenda Bento');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Sarah','37518236839','Fazenda Sarah');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Aurora','37829156221','Fazenda Aurora');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Gabriela','37078160491','Fazenda Gabriela');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Lucca','37878692285','Fazenda Lucca');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Bruno','37935951573','Fazenda Bruno');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Henry','37143050199','Fazenda Henry');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Antônio','37671441669','Fazenda Antônio');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Clara','37986571629','Fazenda Ana Clara');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Amanda','37904219239','Fazenda Amanda');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Kaique','37650794861','Fazenda Kaique');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Olívia','37816464626','Fazenda Olívia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Caleb','37265687610','Fazenda Caleb');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Louise','37460540936','Fazenda Louise');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Valentina','37152808261','Fazenda Maria Valentina');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Nathan','37135704466','Fazenda Nathan');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Enzo Gabriel','37112266260','Fazenda Enzo Gabriel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Sophie','37725005931','Fazenda Sophie');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Milena','37324905451','Fazenda Milena');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('João Miguel','37032258985','Fazenda João Miguel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Stella','37731232835','Fazenda Stella');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Luiz Gustavo','37492882427','Fazenda Luiz Gustavo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ian','37388504492','Fazenda Ian');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Raul','37992126309','Fazenda Raul');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Cecília','37038226569','Fazenda Cecília');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ana Vitória','37221071521','Fazenda Ana Vitória');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Nicolas','37207429150','Fazenda Nicolas');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Pedro Miguel','37504337093','Fazenda Pedro Miguel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('João','37262470622','Fazenda João');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Mariah','37948690606','Fazenda Mariah');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Luan','37118652351','Fazenda Luan');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Pietra','37543780743','Fazenda Pietra');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Isis','37224093164','Fazenda Isis');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Manuela','37369225461','Fazenda Manuela');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Luiza','37460839813','Fazenda Maria Luiza');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('João Lucas','37164574981','Fazenda João Lucas');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Allana','37741674210','Fazenda Allana');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Vitória','37749823715','Fazenda Vitória');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Samuel','37467924322','Fazenda Samuel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Eduarda','37799866298','Fazenda Eduarda');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ruan','37267240622','Fazenda Ruan');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ryan','37368060493','Fazenda Ryan');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Sophia','37407384003','Fazenda Maria Sophia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Miguel','37356181243','Fazenda Miguel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Isabelly','37562378418','Fazenda Isabelly');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Enrico','37928666177','Fazenda Enrico');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Breno','37610238363','Fazenda Breno');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Luiz Felipe','37294431373','Fazenda Luiz Felipe');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Henrique','37524491108','Fazenda Henrique');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Joana','37550684520','Fazenda Joana');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Rafaela','37937381429','Fazenda Rafaela');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Gabriel','37441890001','Fazenda Gabriel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Pedro Henrique','37974932485','Fazenda Pedro Henrique');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Laura','37748576628','Fazenda Maria Laura');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Joaquim','37120219229','Fazenda Joaquim');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Helena','37181685824','Fazenda Maria Helena');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Mirella','37718576239','Fazenda Mirella');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Rodrigo','37904925958','Fazenda Rodrigo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('João Guilherme','37997156748','Fazenda João Guilherme');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Davi Luiz','37863610343','Fazenda Davi Luiz');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Liz','37522924519','Fazenda Liz');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Lorenzo','37093818483','Fazenda Lorenzo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Isabel','37918380315','Fazenda Isabel');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Yuri','37409602063','Fazenda Yuri');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Letícia','37940321170','Fazenda Letícia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Ayla','37006935967','Fazenda Ayla');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Bianca','37316376583','Fazenda Bianca');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Vitória','37933966083','Fazenda Maria Vitória');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Henrique','37330924520','Fazenda Henrique');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Emilly','37734461120','Fazenda Emilly');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Valentina','37197583191','Fazenda Valentina');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Eduardo','37049142594','Fazenda Eduardo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Yago','37220676889','Fazenda Yago');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Carolina','37208957277','Fazenda Carolina');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Kauê','37288193353','Fazenda Kauê');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Bryan','37151228906','Fazenda Bryan');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Júlia','37988783510','Fazenda Júlia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Luna','37530450885','Fazenda Luna');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Francisco','37776998789','Fazenda Francisco');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Eloá','37783561913','Fazenda Eloá');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Théo','37493438527','Fazenda Théo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Benjamin','37359949828','Fazenda Benjamin');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Maria Júlia','37756002204','Fazenda Maria Júlia');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Augusto','37085339281','Fazenda Augusto');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('Danilo','37045940832','Fazenda Danilo');
INSERT INTO cliente(nome_cliente, telefone_cliente, fazenda_cliente) VALUES('João Victor','37001712932','Fazenda João Victor');


-- Dados tabela leilao

INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Sindicato Rural de Bambui','25-9-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','Associacao dos produtores','22-9-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','IFMG de Bambuí','26-9-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Sindicato Rural de Bambui','12-8-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','Sindicato Rural de Candeias','22-9-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','Sindicato Rural de Candeias','4-9-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','Sindicato Rural de Bambui','26-9-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','IFMG de Bambuí','3-5-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','IFMG de Bambuí','17-6-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','Sindicato Rural de Bambui','11-10-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','Associacao dos produtores','10-9-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','Sindicato Rural de Bambui','22-2-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Associacao dos produtores','9-8-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','IFMG de Bambuí','1-11-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','Sindicato Rural de Bambui','26-4-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','Sindicato Rural de Bambui','10-10-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','IFMG de Bambuí','10-7-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Sindicato Rural de Bambui','18-2-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','Sindicato Rural de Bambui','1-1-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','Sindicato Rural de Candeias','21-3-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','Sindicato Rural de Candeias','3-5-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Sindicato Rural de Bambui','5-1-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','Associacao dos produtores','19-9-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','Sindicato Rural de Candeias','27-10-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','Sindicato Rural de Candeias','16-12-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Sindicato Rural de Bambui','6-12-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','Sindicato Rural de Bambui','3-12-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','Associacao dos produtores','7-2-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Associacao dos produtores','20-7-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','Associacao dos produtores','14-3-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','Sindicato Rural de Bambui','7-8-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','Sindicato Rural de Candeias','9-3-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','IFMG de Bambuí','12-4-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Associacao dos produtores','4-6-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','IFMG de Bambuí','23-3-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','Sindicato Rural de Candeias','9-3-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','IFMG de Bambuí','4-8-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Leandro Leilões Sindicato','IFMG de Bambuí','21-11-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Associacao dos produtores','23-2-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','IFMG de Bambuí','15-10-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Sindicato Rural de Candeias','19-7-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','IFMG de Bambuí','22-5-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Associacao dos produtores','22-10-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','IFMG de Bambuí','23-8-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','Sindicato Rural de Bambui','22-10-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','Sindicato Rural de Candeias','3-10-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','IFMG de Bambuí','15-2-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Hudson Leilões Sindicato','Sindicato Rural de Candeias','17-11-2011');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Pedro Leilões Sindicato','IFMG de Bambuí','3-12-2010');
INSERT INTO leilao(nome_leilao, local_leilao, data_leilao) VALUES('Silvano Leilões Sindicato','Associacao dos produtores','14-4-2010');


-- Dados tabela lote

INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(4,'F',9,4,9,'Defesa',8835,5,95,99,44);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(4,'F',1,1,5,'Venda',6973,2,175,83,21);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(26,'M',1,10,1,'Venda',9058,0,84,196,29);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(3,'M',2,7,7,'Venda',3784,10,45,10,38);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(30,'M',7,9,7,'Venda',9878,1,133,69,39);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(26,'M',9,10,6,'Venda',8324,1,128,120,42);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(18,'F',5,3,7,'Venda',9618,0,168,13,4);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(30,'F',9,3,3,'',2840,1,35,43,12);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(7,'M',8,3,2,'Venda',2348,4,114,17,9);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(19,'F',3,9,2,'',4336,4,135,156,15);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'F',1,2,10,'Venda',2060,8,157,45,18);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(10,'M',3,1,9,'Defesa',2402,12,92,14,1);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(27,'F',6,5,3,'Venda',4154,5,195,172,16);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(23,'M',3,2,6,'Venda',8314,0,185,21,43);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(27,'M',4,1,7,'Defesa',8880,2,19,46,29);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(21,'M',5,6,5,'',5350,12,49,8,1);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(27,'M',8,10,5,'',9498,11,73,47,42);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(19,'F',6,9,2,'Venda',2778,10,79,14,43);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'F',8,2,6,'Venda',5131,5,27,150,9);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(15,'M',4,3,2,'Venda',8748,11,67,135,8);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(11,'M',5,2,2,'Defesa',9303,12,167,92,14);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(27,'M',6,6,6,'',7599,9,176,192,21);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(10,'F',1,9,4,'Venda',8553,7,43,135,27);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(19,'M',6,10,3,'Defesa',6987,11,18,113,48);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(15,'F',9,9,9,'',3046,2,19,174,5);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(1,'M',6,5,9,'',8006,11,44,61,22);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(14,'M',10,10,6,'Defesa',7184,0,51,105,28);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(30,'F',6,2,2,'Venda',2589,1,133,26,29);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(19,'M',4,3,5,'Venda',8920,0,72,196,37);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(19,'F',9,5,2,'Defesa',3384,11,126,74,44);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(28,'M',8,3,2,'',8902,5,155,185,26);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(7,'M',1,1,10,'',7788,7,96,138,42);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(25,'F',5,7,10,'',5307,8,126,141,1);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(6,'M',5,5,8,'Defesa',4350,0,78,171,26);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(24,'M',7,4,3,'Venda',9182,4,85,168,37);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(23,'M',1,3,3,'Defesa',2049,2,69,69,2);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(8,'M',5,2,5,'Venda',8848,5,48,24,38);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(10,'M',3,5,3,'Venda',9828,8,95,101,35);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(28,'F',7,6,3,'Venda',6141,3,15,154,47);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(13,'F',8,7,1,'Venda',4827,6,18,190,44);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(7,'F',9,9,4,'Venda',3549,0,114,139,47);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(20,'F',4,10,9,'Defesa',8735,4,194,50,38);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(5,'F',1,5,5,'',7731,10,20,131,3);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(2,'F',8,8,2,'',5301,4,90,63,5);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(23,'F',6,4,8,'Venda',5607,0,10,123,40);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(24,'M',1,9,10,'Venda',9298,6,145,188,38);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(14,'F',3,2,10,'Venda',3469,0,102,93,21);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(23,'F',9,6,1,'',5881,8,53,57,37);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'F',10,3,9,'Venda',7822,11,168,194,13);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(28,'F',10,9,2,'Venda',5150,6,31,103,26);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(20,'F',7,7,3,'Defesa',9049,0,132,128,22);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(23,'F',4,7,3,'Venda',2853,9,25,75,30);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(10,'M',1,7,1,'',8125,4,46,39,30);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(12,'F',3,9,10,'Venda',7777,9,72,105,19);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(11,'F',1,6,7,'Venda',6834,0,55,130,25);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(28,'M',4,5,3,'Venda',8017,1,6,43,22);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(4,'M',4,7,3,'Defesa',9644,4,195,149,31);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'F',8,5,5,'',7730,3,14,141,13);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(12,'M',8,7,4,'',2178,9,173,70,50);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(23,'F',6,3,1,'Venda',4860,12,30,94,46);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(27,'M',10,10,7,'Venda',7616,6,60,4,14);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(2,'M',8,5,7,'Defesa',2808,8,193,173,10);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(14,'F',10,1,5,'',8260,6,19,67,39);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(19,'F',1,1,10,'Defesa',5006,11,32,116,17);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(6,'M',10,6,8,'Venda',2467,10,128,74,40);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(5,'F',2,7,3,'Defesa',3977,0,103,59,38);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(11,'M',5,10,9,'Defesa',5180,1,95,121,6);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'M',9,8,9,'Venda',4937,3,193,186,14);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(6,'M',2,10,7,'Venda',3364,0,22,46,36);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(20,'M',3,4,3,'Venda',7455,2,35,158,36);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(10,'M',6,3,7,'Venda',6333,0,92,149,35);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(27,'M',6,3,6,'Venda',2852,0,123,127,6);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(14,'M',3,5,3,'Defesa',7415,4,193,77,40);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(22,'M',2,2,6,'Venda',8905,5,151,160,11);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(18,'F',10,2,7,'',8626,12,166,147,2);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(25,'M',10,4,5,'Venda',5744,1,10,161,1);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(20,'M',9,4,8,'Defesa',7681,2,77,13,36);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'M',9,10,2,'Venda',5440,10,195,31,20);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(30,'F',2,5,1,'',2134,0,4,45,12);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(20,'M',4,3,1,'Venda',3729,6,75,148,16);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(6,'M',7,4,2,'Venda',7484,0,72,18,38);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(18,'F',10,3,9,'Venda',9369,2,68,112,16);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(18,'F',7,4,1,'Venda',9930,1,200,58,48);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(29,'F',6,1,1,'Venda',2418,0,55,179,8);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(22,'F',10,10,9,'Venda',7485,6,32,29,42);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(8,'M',9,2,2,'Venda',8804,4,25,4,38);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(23,'F',10,1,1,'Venda',6886,11,27,197,39);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'F',1,8,10,'',5120,9,95,35,20);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(8,'F',1,3,1,'Venda',4259,3,91,137,26);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(4,'F',3,4,9,'Venda',5657,0,57,92,44);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'F',7,9,4,'Venda',4841,8,120,167,32);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(8,'F',10,9,5,'Defesa',2814,8,173,198,16);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(15,'M',9,5,1,'Venda',5757,1,195,46,18);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(20,'F',5,4,2,'Defesa',6714,7,180,1,16);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(22,'M',7,10,4,'Venda',8820,0,140,28,40);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(4,'M',4,9,4,'',5915,7,127,83,9);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(5,'F',7,10,2,'',6346,12,140,51,21);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(21,'M',2,3,10,'',5772,3,120,3,44);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(23,'M',5,1,5,'Venda',2525,7,118,70,45);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(16,'F',1,4,7,'Defesa',2833,10,112,93,15);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(12,'F',10,9,2,'Venda',9013,9,187,121,9);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(6,'F',4,10,4,'Venda',7849,1,189,135,34);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(22,'F',6,3,5,'Defesa',8419,12,24,102,13);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(23,'F',2,7,1,'Venda',6210,9,124,110,40);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(4,'M',5,7,10,'Venda',3154,8,7,58,20);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(2,'M',1,5,5,'Defesa',9183,5,75,193,15);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(13,'M',4,3,4,'Defesa',6287,4,198,26,20);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(27,'M',3,10,3,'Venda',7134,8,135,86,16);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(9,'M',8,10,2,'Defesa',2558,0,19,31,34);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(19,'M',7,3,1,'',3229,3,104,24,8);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(4,'M',8,9,7,'',8216,5,77,148,39);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(16,'M',2,6,4,'',7359,0,162,164,25);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(20,'F',10,8,9,'Defesa',6760,12,4,193,8);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(16,'M',1,10,5,'',3914,12,14,84,45);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(22,'F',3,10,5,'',9826,9,77,139,37);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(13,'M',1,4,2,'Defesa',2883,9,119,118,33);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'F',9,2,3,'Venda',7522,5,138,73,3);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(2,'F',6,4,3,'Venda',4706,8,103,57,3);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(17,'M',4,1,7,'Defesa',3231,0,99,149,24);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(1,'F',10,7,8,'Venda',8939,6,141,176,32);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(26,'M',9,3,8,'',5073,2,102,63,12);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(5,'F',10,4,8,'',2010,1,167,139,17);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(3,'F',10,5,9,'Venda',8936,5,99,79,49);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(29,'M',4,1,3,'Defesa',9940,2,25,195,39);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(5,'M',8,1,4,'Venda',2064,7,112,102,43);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(24,'F',9,9,9,'Defesa',4042,4,106,155,24);
INSERT INTO lote(quantidade_lote, sexo_lote,idade,comissao_compra,comissao_venda,situacao_arremate,valor,parcelas,id_cliente_vendedor,id_cliente_comprador,id_leilao) VALUES(12,'F',1,2,3,'Venda',7277,2,64,178,40);


-- Para a quarta etapa a inserção de contas não e necessaria pois ela sera feita por gatilho 
-- Dados tabela contas


/*
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('27-9-2010',5737,45,6);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-12-2010',6918,127,21);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('18-3-2010',9406,36,31);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('20-6-2011',2079,20,40);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('11-7-2010',7416,126,27);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('1-11-2010',5807,46,36);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('22-8-2010',5327,124,16);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('11-3-2011',2265,3,25);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('8-11-2011',6932,50,31);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('2-5-2011',8146,71,49);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('21-10-2011',8587,52,11);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('27-7-2010',5791,76,47);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('17-8-2011',4686,24,49);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('18-1-2011',4598,43,46);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('14-6-2011',8773,2,24);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('28-8-2010',4338,110,40);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('22-4-2010',5312,127,11);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('23-3-2011',8872,100,6);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-5-2010',6436,5,3);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('9-11-2011',8658,48,40);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('18-7-2010',2272,20,40);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-10-2011',9748,102,33);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('13-5-2010',6797,51,24);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('19-4-2011',6383,120,47);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('17-1-2010',4206,69,27);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('12-6-2010',6537,34,28);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('27-7-2011',5200,90,14);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('21-6-2010',3015,109,29);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('9-3-2011',7395,86,17);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('12-11-2011',5307,19,7);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('16-3-2011',5691,75,35);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('7-5-2010',6630,102,5);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('18-5-2010',7094,75,49);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('20-1-2011',5712,37,12);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('5-4-2011',7912,108,8);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('17-3-2010',4064,125,46);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('15-3-2011',2895,48,15);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-1-2011',5221,91,27);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('8-3-2010',2656,124,31);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('13-12-2010',3461,49,46);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('17-3-2010',6578,53,12);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-8-2010',7883,31,37);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('17-4-2011',6410,59,50);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('11-12-2011',9576,29,33);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('8-1-2011',7656,119,43);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('27-3-2010',2905,32,9);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('7-3-2010',9788,34,50);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('15-1-2011',3632,15,41);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('1-4-2010',6086,2,9);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('21-3-2011',8124,22,1);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('3-1-2010',5639,111,26);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('5-1-2010',2479,9,7);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-9-2011',3862,127,26);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('26-1-2010',9490,54,24);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('21-9-2010',4927,125,49);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('13-4-2011',5057,18,44);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('27-9-2011',3353,49,19);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-3-2011',3104,16,40);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('15-1-2010',5725,60,35);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('2-9-2010',3974,112,3);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('18-2-2011',7090,64,36);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('22-7-2010',3180,44,34);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('18-7-2011',3949,27,35);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('14-5-2011',2157,125,45);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('9-2-2010',7197,24,36);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('23-8-2011',2595,47,50);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('13-1-2011',8884,83,46);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('12-12-2010',3474,116,8);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('12-5-2011',4830,25,23);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('26-4-2010',3521,46,33);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('2-2-2010',5462,83,25);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('4-9-2010',7032,73,16);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('14-10-2011',8258,59,18);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('2-8-2010',8696,20,11);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('8-8-2011',8580,70,35);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-2-2010',2425,73,45);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('13-4-2010',7411,90,26);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('26-11-2011',7673,77,29);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('1-4-2011',5764,87,21);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('13-8-2010',9678,103,27);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('9-4-2011',5370,11,4);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('3-5-2010',7482,1,26);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('7-11-2011',4587,86,5);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('18-9-2010',4783,19,18);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('7-2-2010',3248,87,38);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('9-10-2011',9536,101,4);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('13-9-2010',7666,113,15);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('16-6-2011',7279,36,34);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('16-12-2011',4724,109,42);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('22-1-2010',8312,9,2);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-12-2010',6052,31,15);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('13-1-2011',6541,31,41);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('20-12-2011',9440,21,49);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('2-8-2010',6744,79,48);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('11-2-2010',8815,37,47);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('6-9-2010',9998,121,18);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('24-12-2011',5219,88,11);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('21-7-2010',7347,86,30);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('11-3-2010',3427,50,50);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('6-10-2011',6379,111,11);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('1-11-2011',6946,108,40);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('8-1-2010',9643,34,18);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('27-7-2011',6509,122,42);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('10-11-2011',5919,93,12);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('26-12-2010',3992,40,26);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('25-10-2011',3273,84,9);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('22-6-2010',3044,86,2);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('22-8-2010',4358,5,7);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('17-6-2010',9339,67,44);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('5-5-2010',5037,43,7);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('25-5-2010',7056,22,36);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('12-4-2011',6374,43,38);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('3-6-2010',7016,89,37);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('28-8-2011',8113,114,5);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('27-12-2010',8933,73,26);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('14-1-2011',4195,73,9);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('20-3-2011',6773,62,3);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('17-5-2011',9535,27,16);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('14-8-2011',8821,74,6);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('7-9-2010',2013,27,50);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('22-7-2011',2408,36,18);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('3-2-2010',9708,105,3);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('19-1-2011',7656,52,19);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('22-3-2011',2610,114,43);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('14-10-2010',6581,10,26);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('28-3-2010',3575,66,49);
INSERT INTO contas(vencimento, total,id_lote,id_cliente) VALUES('13-5-2010',9191,68,26);

*/